"""CNN components for EPIC sequence experiments."""

from .data import prepare_oriented_cnn_batch
from .cascade import (
    ConditionalLocalizerB,
    DNA_CHANNELS,
    FiLMAdapter,
    LOCAL_BLOCK_SETTINGS,
    REGIONAL_CONDITION_CHANNELS,
    REGIONAL_LATENT_CHANNELS,
    REGION_SIZE,
    RegionalDetectorA,
    RegionalRateDetectorA,
    broadcast_r16_condition,
    encode_raw_dna_six_channel,
    reverse_complement_six_channel,
    theoretical_receptive_field,
)
from .cascade_data import (
    RegionalBatch,
    RegionalFeatureCache,
    RegionalWindowGenerator,
    predict_contig_to_regional_cache,
)
from .directml import (
    DirectMLAdam,
    StableBCEWithLogits,
    dml_bce_with_logits,
    dml_weighted_bce_with_logits,
    dml_weighted_huber,
    dml_weighted_profile_bce_with_logits,
)
from .evaluation import (
    LoadedCNNCheckpoint,
    LoadedPresenceIntensityCheckpoint,
    ProfileEvaluationResult,
    evaluate_profile_model,
    evaluate_presence_intensity_model,
    load_cnn_baseline_checkpoint,
    load_cnn_presence_intensity_checkpoint,
)
from .model import (
    CNNBackbone,
    CNNBaseline,
    CNNPresenceIntensity,
    DEFAULT_BLOCK_SETTINGS,
    ResidualBlock,
    create_cnn_baseline,
    create_cnn_presence_intensity,
)
from .profile import (
    ProfileBatch,
    ProfileWindowConfig,
    ProfileWindowGenerator,
    build_profile_tile_index,
    forward_both_strands,
    forward_both_strands_multitask,
)

__all__ = [
    "CNNBackbone",
    "CNNBaseline",
    "CNNPresenceIntensity",
    "ConditionalLocalizerB",
    "DEFAULT_BLOCK_SETTINGS",
    "DNA_CHANNELS",
    "DirectMLAdam",
    "FiLMAdapter",
    "LOCAL_BLOCK_SETTINGS",
    "LoadedCNNCheckpoint",
    "LoadedPresenceIntensityCheckpoint",
    "ProfileBatch",
    "ProfileEvaluationResult",
    "ProfileWindowConfig",
    "ProfileWindowGenerator",
    "REGIONAL_CONDITION_CHANNELS",
    "REGIONAL_LATENT_CHANNELS",
    "REGION_SIZE",
    "RegionalBatch",
    "RegionalDetectorA",
    "RegionalRateDetectorA",
    "RegionalFeatureCache",
    "RegionalWindowGenerator",
    "ResidualBlock",
    "StableBCEWithLogits",
    "create_cnn_baseline",
    "create_cnn_presence_intensity",
    "build_profile_tile_index",
    "broadcast_r16_condition",
    "dml_bce_with_logits",
    "dml_weighted_bce_with_logits",
    "dml_weighted_huber",
    "dml_weighted_profile_bce_with_logits",
    "evaluate_profile_model",
    "evaluate_presence_intensity_model",
    "encode_raw_dna_six_channel",
    "forward_both_strands",
    "forward_both_strands_multitask",
    "load_cnn_baseline_checkpoint",
    "load_cnn_presence_intensity_checkpoint",
    "prepare_oriented_cnn_batch",
    "predict_contig_to_regional_cache",
    "reverse_complement_six_channel",
    "theoretical_receptive_field",
]
